
default ton_ev_hangouts_wine_intro = Event(id="ton_ev_hangouts_wine_intro", label="nt_he_wine_intro", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_drinking")
default ton_ev_hangouts_firewhisky_intro = Event(id="ton_ev_hangouts_firewhisky_intro", label="nt_he_firewhisky_intro", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_drinking")
default ton_ev_hangouts_firewhisky_e1 = Event(id="ton_ev_hangouts_firewhisky_e1", label="nt_he_firewhisky_E1", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_drinking")
default ton_ev_hangouts_firewhisky_e2 = Event(id="ton_ev_hangouts_firewhisky_e2", label="nt_he_firewhisky_E2", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_drinking")
default ton_ev_hangouts_firewhisky_e3 = Event(id="ton_ev_hangouts_firewhisky_e3", label="nt_he_firewhisky_E3", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_drinking")
default ton_ev_hangouts_firewhisky_e4 = Event(id="ton_ev_hangouts_firewhisky_e4", label="nt_he_firewhisky_E4", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_drinking")

default ton_ev_hangouts_story_e1 = Event(id="ton_ev_hangouts_story_e1", label="nt_he_story_intro_E1", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_story")
default ton_ev_hangouts_story_e2 = Event(id="ton_ev_hangouts_story_e2", label="nt_he_story_intro_E2", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_story")
default ton_ev_hangouts_story_e3 = Event(id="ton_ev_hangouts_story_e3", label="nt_he_story_intro_E3", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_story")
default ton_ev_hangouts_story_e4 = Event(id="ton_ev_hangouts_story_e4", label="nt_he_story_intro_E4", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_story")
default ton_ev_hangouts_story_e5 = Event(id="ton_ev_hangouts_story_e5", label="nt_he_story_intro_E5", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_story")
default ton_ev_hangouts_story_e6 = Event(id="ton_ev_hangouts_story_e6", label="nt_he_story_E6", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_story")
default ton_ev_hangouts_story_e7 = Event(id="ton_ev_hangouts_story_e7", label="nt_he_story_intro_E7", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_story")
default ton_ev_hangouts_story_e8 = Event(id="ton_ev_hangouts_story_e8", label="nt_he_story_E8", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_story")
default ton_ev_hangouts_story_e9 = Event(id="ton_ev_hangouts_story_e9", label="nt_he_story_intro_E9", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_story")
default ton_ev_hangouts_story_e10 = Event(id="ton_ev_hangouts_story_e10", label="nt_he_story_intro_E10", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_story")
default ton_ev_hangouts_story_e11 = Event(id="ton_ev_hangouts_story_e11", label="nt_he_story_E11", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_story")
default ton_ev_hangouts_story_e12 = Event(id="ton_ev_hangouts_story_e12", label="nt_he_story_E12", autoenqueue=True, autodequeue=False, repeat=False, queue="ton_eventqueue_hangouts_story")
