# Public requests

default her_ev_flirt_students_t1_e1 = Event(id="her_ev_flirt_students_t1_e1", label="hg_pr_flirt_T1_E1", req="game.daytime == False")
default her_ev_flirt_students_t1_e2 = Event(id="her_ev_flirt_students_t1_e2", label="hg_pr_flirt_T1_E2", req="game.daytime == False")
default her_ev_flirt_students_t1_e3 = Event(id="her_ev_flirt_students_t1_e3", label="hg_pr_flirt_T1_E3", req="game.daytime == False")
default her_ev_flirt_students_t2_e1 = Event(id="her_ev_flirt_students_t2_e1", label="hg_pr_flirt_T2_E1", req="game.daytime == False")
default her_ev_flirt_students_t2_e2 = Event(id="her_ev_flirt_students_t2_e2", label="hg_pr_flirt_T2_E2", req="game.daytime == False")
default her_ev_flirt_students_t2_e3 = Event(id="her_ev_flirt_students_t2_e3", label="hg_pr_flirt_T2_E3", req="game.daytime == False")
default her_ev_flirt_students_t3_e1 = Event(id="her_ev_flirt_students_t3_e1", label="hg_pr_flirt_T3_E1", req="game.daytime == False")
default her_ev_flirt_students_t3_e2 = Event(id="her_ev_flirt_students_t3_e2", label="hg_pr_flirt_T3_E2", req="game.daytime == False")
default her_ev_flirt_students_t3_e3 = Event(id="her_ev_flirt_students_t3_e3", label="hg_pr_flirt_T3_E3", req="game.daytime == False")

default her_ev_flirt_students_t1_e1_hub = Event(id="her_ev_flirt_students_t1_e1_hub", label="hg_pr_flirt", req="states.her.tier == 1", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_students", subevents=["her_ev_flirt_students_t1_e1"])
default her_ev_flirt_students_t1_e2_hub = Event(id="her_ev_flirt_students_t1_e2_hub", label="hg_pr_flirt", req="states.her.tier == 1", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_students", subevents=["her_ev_flirt_students_t1_e2"])
default her_ev_flirt_students_t1_e3_hub = Event(id="her_ev_flirt_students_t1_e3_hub", label="hg_pr_flirt", req="states.her.tier == 1", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_students", subevents=["her_ev_flirt_students_t1_e3"])
default her_ev_flirt_students_t2_e1_hub = Event(id="her_ev_flirt_students_t2_e1_hub", label="hg_pr_flirt", req="states.her.tier == 2", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_students", subevents=["her_ev_flirt_students_t2_e1"])
default her_ev_flirt_students_t2_e2_hub = Event(id="her_ev_flirt_students_t2_e2_hub", label="hg_pr_flirt", req="states.her.tier == 2", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_students", subevents=["her_ev_flirt_students_t2_e2"])
default her_ev_flirt_students_t2_e3_hub = Event(id="her_ev_flirt_students_t2_e3_hub", label="hg_pr_flirt", req="states.her.tier == 2", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_students", subevents=["her_ev_flirt_students_t2_e3"])
default her_ev_flirt_students_t3_e1_hub = Event(id="her_ev_flirt_students_t3_e1_hub", label="hg_pr_flirt", req="states.her.tier >= 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_students", subevents=["her_ev_flirt_students_t3_e1"])
default her_ev_flirt_students_t3_e2_hub = Event(id="her_ev_flirt_students_t3_e2_hub", label="hg_pr_flirt", req="states.her.tier >= 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_students", subevents=["her_ev_flirt_students_t3_e2"])
default her_ev_flirt_students_t3_e3_hub = Event(id="her_ev_flirt_students_t3_e3_hub", label="hg_pr_flirt", req="states.her.tier >= 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_students", subevents=["her_ev_flirt_students_t3_e3"])

default her_ev_flirt_teachers_t1_e1 = Event(id="her_ev_flirt_teachers_t1_e1", label="hg_pr_flirt_teacher_T1_E1", req="game.daytime == False")
default her_ev_flirt_teachers_t1_e2 = Event(id="her_ev_flirt_teachers_t1_e2", label="hg_pr_flirt_teacher_T1_E2", req="game.daytime == False")
default her_ev_flirt_teachers_t1_e3 = Event(id="her_ev_flirt_teachers_t1_e3", label="hg_pr_flirt_teacher_T1_E3", req="game.daytime == False")
default her_ev_flirt_teachers_t2_e1 = Event(id="her_ev_flirt_teachers_t2_e1", label="hg_pr_flirt_teacher_T2_E1", req="game.daytime == False")
default her_ev_flirt_teachers_t2_e2 = Event(id="her_ev_flirt_teachers_t2_e2", label="hg_pr_flirt_teacher_T2_E2", req="game.daytime == False")
default her_ev_flirt_teachers_t2_e3 = Event(id="her_ev_flirt_teachers_t2_e3", label="hg_pr_flirt_teacher_T2_E3", req="game.daytime == False")
default her_ev_flirt_teachers_t3_e1 = Event(id="her_ev_flirt_teachers_t3_e1", label="hg_pr_flirt_teacher_T3_E1", req="game.daytime == False")
default her_ev_flirt_teachers_t3_e2 = Event(id="her_ev_flirt_teachers_t3_e2", label="hg_pr_flirt_teacher_T3_E2", req="game.daytime == False")
default her_ev_flirt_teachers_t3_e3 = Event(id="her_ev_flirt_teachers_t3_e3", label="hg_pr_flirt_teacher_T3_E3", req="game.daytime == False")

default her_ev_flirt_teachers_t1_e1_hub = Event(id="her_ev_flirt_teachers_t1_e1_hub", label="hg_pr_flirt_teacher", req="states.her.tier == 1", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_teachers", subevents=["her_ev_flirt_teachers_t1_e1"])
default her_ev_flirt_teachers_t1_e2_hub = Event(id="her_ev_flirt_teachers_t1_e2_hub", label="hg_pr_flirt_teacher", req="states.her.tier == 1", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_teachers", subevents=["her_ev_flirt_teachers_t1_e2"])
default her_ev_flirt_teachers_t1_e3_hub = Event(id="her_ev_flirt_teachers_t1_e3_hub", label="hg_pr_flirt_teacher", req="states.her.tier == 1", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_teachers", subevents=["her_ev_flirt_teachers_t1_e3"])
default her_ev_flirt_teachers_t2_e1_hub = Event(id="her_ev_flirt_teachers_t2_e1_hub", label="hg_pr_flirt_teacher", req="states.her.tier == 2", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_teachers", subevents=["her_ev_flirt_teachers_t2_e1"])
default her_ev_flirt_teachers_t2_e2_hub = Event(id="her_ev_flirt_teachers_t2_e2_hub", label="hg_pr_flirt_teacher", req="states.her.tier == 2", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_teachers", subevents=["her_ev_flirt_teachers_t2_e2"])
default her_ev_flirt_teachers_t2_e3_hub = Event(id="her_ev_flirt_teachers_t2_e3_hub", label="hg_pr_flirt_teacher", req="states.her.tier == 2", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_teachers", subevents=["her_ev_flirt_teachers_t2_e3"])
default her_ev_flirt_teachers_t3_e1_hub = Event(id="her_ev_flirt_teachers_t3_e1_hub", label="hg_pr_flirt_teacher", req="states.her.tier >= 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_teachers", subevents=["her_ev_flirt_teachers_t3_e1"])
default her_ev_flirt_teachers_t3_e2_hub = Event(id="her_ev_flirt_teachers_t3_e2_hub", label="hg_pr_flirt_teacher", req="states.her.tier >= 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_teachers", subevents=["her_ev_flirt_teachers_t3_e2"])
default her_ev_flirt_teachers_t3_e3_hub = Event(id="her_ev_flirt_teachers_t3_e3_hub", label="hg_pr_flirt_teacher", req="states.her.tier >= 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flirt_teachers", subevents=["her_ev_flirt_teachers_t3_e3"])

default her_ev_grope_public_t2_e1 = Event(id="her_ev_grope_public_t2_e1", label="hg_pr_grope_T2_E1", req="game.daytime == False")
default her_ev_grope_public_t2_e2 = Event(id="her_ev_grope_public_t2_e2", label="hg_pr_grope_T2_E2", req="game.daytime == False")
default her_ev_grope_public_t2_e3 = Event(id="her_ev_grope_public_t2_e3", label="hg_pr_grope_T2_E3", req="game.daytime == False")
default her_ev_grope_public_t3_e1 = Event(id="her_ev_grope_public_t3_e1", label="hg_pr_grope_T3_E1", req="game.daytime == False")
default her_ev_grope_public_t3_e2 = Event(id="her_ev_grope_public_t3_e2", label="hg_pr_grope_T3_E2", req="game.daytime == False")
default her_ev_grope_public_t3_e3 = Event(id="her_ev_grope_public_t3_e3", label="hg_pr_grope_T3_E3", req="game.daytime == False")
default her_ev_grope_public_t4_e1 = Event(id="her_ev_grope_public_t4_e1", label="hg_pr_grope_T4_E1", req="game.daytime == False")
default her_ev_grope_public_t4_e2 = Event(id="her_ev_grope_public_t4_e2", label="hg_pr_grope_T4_E2", req="game.daytime == False")
default her_ev_grope_public_t4_e3 = Event(id="her_ev_grope_public_t4_e3", label="hg_pr_grope_T4_E3", req="game.daytime == False")

default her_ev_grope_public_t1_e1_hub = Event(id="her_ev_grope_public_t1_e1_hub", label="hg_pr_grope_fail", req="states.her.tier == 1", autoenqueue=True, autodequeue=False, queue="her_eventqueue_grope_public")
default her_ev_grope_public_t2_e1_hub = Event(id="her_ev_grope_public_t2_e1_hub", label="hg_pr_grope", req="states.her.tier == 2", autoenqueue=True, autodequeue=False, queue="her_eventqueue_grope_public", subevents=["her_ev_grope_public_t2_e1"])
default her_ev_grope_public_t2_e2_hub = Event(id="her_ev_grope_public_t2_e2_hub", label="hg_pr_grope", req="states.her.tier == 2", autoenqueue=True, autodequeue=False, queue="her_eventqueue_grope_public", subevents=["her_ev_grope_public_t2_e2"])
default her_ev_grope_public_t2_e3_hub = Event(id="her_ev_grope_public_t2_e3_hub", label="hg_pr_grope", req="states.her.tier == 2", autoenqueue=True, autodequeue=False, queue="her_eventqueue_grope_public", subevents=["her_ev_grope_public_t2_e3"])
default her_ev_grope_public_t3_e1_hub = Event(id="her_ev_grope_public_t3_e1_hub", label="hg_pr_grope", req="states.her.tier == 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_grope_public", subevents=["her_ev_grope_public_t3_e1"])
default her_ev_grope_public_t3_e2_hub = Event(id="her_ev_grope_public_t3_e2_hub", label="hg_pr_grope", req="states.her.tier == 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_grope_public", subevents=["her_ev_grope_public_t3_e2"])
default her_ev_grope_public_t3_e3_hub = Event(id="her_ev_grope_public_t3_e3_hub", label="hg_pr_grope", req="states.her.tier == 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_grope_public", subevents=["her_ev_grope_public_t3_e3"])
default her_ev_grope_public_t4_e1_hub = Event(id="her_ev_grope_public_t4_e1_hub", label="hg_pr_grope", req="states.her.tier >= 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_grope_public", subevents=["her_ev_grope_public_t4_e1"])
default her_ev_grope_public_t4_e2_hub = Event(id="her_ev_grope_public_t4_e2_hub", label="hg_pr_grope", req="states.her.tier >= 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_grope_public", subevents=["her_ev_grope_public_t4_e2"])
default her_ev_grope_public_t4_e3_hub = Event(id="her_ev_grope_public_t4_e3_hub", label="hg_pr_grope", req="states.her.tier >= 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_grope_public", subevents=["her_ev_grope_public_t4_e3"])

default her_ev_flash_public_t3_e1 = Event(id="her_ev_flash_public_t3_e1", label="hg_pr_flash_T3_E1", req="game.daytime == False")
default her_ev_flash_public_t3_e2 = Event(id="her_ev_flash_public_t3_e2", label="hg_pr_flash_T3_E2", req="game.daytime == False")
default her_ev_flash_public_t3_e3 = Event(id="her_ev_flash_public_t3_e3", label="hg_pr_flash_T3_E3", req="game.daytime == False")
default her_ev_flash_public_t4_e1 = Event(id="her_ev_flash_public_t4_e1", label="hg_pr_flash_T4_E1", req="game.daytime == False")
default her_ev_flash_public_t4_e2 = Event(id="her_ev_flash_public_t4_e2", label="hg_pr_flash_T4_E2", req="game.daytime == False")
default her_ev_flash_public_t4_e3 = Event(id="her_ev_flash_public_t4_e3", label="hg_pr_flash_T4_E3", req="game.daytime == False")
default her_ev_flash_public_t5_e1 = Event(id="her_ev_flash_public_t5_e1", label="hg_pr_flash_T5_E1", req="game.daytime == False")
default her_ev_flash_public_t5_e2 = Event(id="her_ev_flash_public_t5_e2", label="hg_pr_flash_T5_E2", req="game.daytime == False")
default her_ev_flash_public_t5_e3 = Event(id="her_ev_flash_public_t5_e3", label="hg_pr_flash_T5_E3", req="game.daytime == False")

default her_ev_flash_public_t1_to_t3 = Event(id="her_ev_flash_public_t1_to_t3", label="hg_pr_flash_fail", req="states.her.tier < 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flash_public")
default her_ev_flash_public_t3_e1_hub = Event(id="her_ev_flash_public_t3_e1_hub", label="hg_pr_flash", req="states.her.tier == 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flash_public", subevents=["her_ev_flash_public_t3_e1"])
default her_ev_flash_public_t3_e2_hub = Event(id="her_ev_flash_public_t3_e2_hub", label="hg_pr_flash", req="states.her.tier == 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flash_public", subevents=["her_ev_flash_public_t3_e2"])
default her_ev_flash_public_t3_e3_hub = Event(id="her_ev_flash_public_t3_e3_hub", label="hg_pr_flash", req="states.her.tier == 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flash_public", subevents=["her_ev_flash_public_t3_e3"])
default her_ev_flash_public_t4_e1_hub = Event(id="her_ev_flash_public_t4_e1_hub", label="hg_pr_flash", req="states.her.tier == 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flash_public", subevents=["her_ev_flash_public_t4_e1"])
default her_ev_flash_public_t4_e2_hub = Event(id="her_ev_flash_public_t4_e2_hub", label="hg_pr_flash", req="states.her.tier == 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flash_public", subevents=["her_ev_flash_public_t4_e2"])
default her_ev_flash_public_t4_e3_hub = Event(id="her_ev_flash_public_t4_e3_hub", label="hg_pr_flash", req="states.her.tier == 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flash_public", subevents=["her_ev_flash_public_t4_e3"])
default her_ev_flash_public_t5_e1_hub = Event(id="her_ev_flash_public_t5_e1_hub", label="hg_pr_flash", req="states.her.tier >= 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flash_public", subevents=["her_ev_flash_public_t5_e1"])
default her_ev_flash_public_t5_e2_hub = Event(id="her_ev_flash_public_t5_e2_hub", label="hg_pr_flash", req="states.her.tier >= 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flash_public", subevents=["her_ev_flash_public_t5_e2"])
default her_ev_flash_public_t5_e3_hub = Event(id="her_ev_flash_public_t5_e3_hub", label="hg_pr_flash", req="states.her.tier >= 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_flash_public", subevents=["her_ev_flash_public_t5_e3"])

default her_ev_kiss_public_t3_e1 = Event(id="her_ev_kiss_public_t3_e1", label="hg_pr_kiss_T3_E1", req="game.daytime==False")
default her_ev_kiss_public_t3_e2 = Event(id="her_ev_kiss_public_t3_e2", label="hg_pr_kiss_T3_E2", req="game.daytime==False")
default her_ev_kiss_public_t3_e3 = Event(id="her_ev_kiss_public_t3_e3", label="hg_pr_kiss_T3_E3", req="game.daytime==False")
default her_ev_kiss_public_t4_e1 = Event(id="her_ev_kiss_public_t4_e1", label="hg_pr_kiss_T4_E1", req="game.daytime==False")
default her_ev_kiss_public_t4_e2 = Event(id="her_ev_kiss_public_t4_e2", label="hg_pr_kiss_T4_E2", req="game.daytime==False")
default her_ev_kiss_public_t4_e3 = Event(id="her_ev_kiss_public_t4_e3", label="hg_pr_kiss_T4_E3", req="game.daytime==False")
default her_ev_kiss_public_t5_e1 = Event(id="her_ev_kiss_public_t5_e1", label="hg_pr_kiss_T5_E1", req="game.daytime==False")
default her_ev_kiss_public_t5_e2 = Event(id="her_ev_kiss_public_t5_e2", label="hg_pr_kiss_T5_E2", req="game.daytime==False")

default her_ev_kiss_public_t1_to_t3 = Event(id="her_ev_kiss_public_t1_to_t3", label="hg_pr_kiss_fail", req="states.her.tier < 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_kiss_public")
default her_ev_kiss_public_t3_e1_hub = Event(id="her_ev_kiss_public_t3_e1_hub", label="hg_pr_kiss", req="states.her.tier == 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_kiss_public", subevents=["her_ev_kiss_public_t3_e1"])
default her_ev_kiss_public_t3_e2_hub = Event(id="her_ev_kiss_public_t3_e2_hub", label="hg_pr_kiss", req="states.her.tier == 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_kiss_public", subevents=["her_ev_kiss_public_t3_e2"])
default her_ev_kiss_public_t3_e3_hub = Event(id="her_ev_kiss_public_t3_e3_hub", label="hg_pr_kiss", req="states.her.tier == 3", autoenqueue=True, autodequeue=False, queue="her_eventqueue_kiss_public", subevents=["her_ev_kiss_public_t3_e3"])
default her_ev_kiss_public_t4_e1_hub = Event(id="her_ev_kiss_public_t4_e1_hub", label="hg_pr_kiss", req="states.her.tier == 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_kiss_public", subevents=["her_ev_kiss_public_t4_e1"])
default her_ev_kiss_public_t4_e2_hub = Event(id="her_ev_kiss_public_t4_e2_hub", label="hg_pr_kiss", req="states.her.tier == 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_kiss_public", subevents=["her_ev_kiss_public_t4_e2"])
default her_ev_kiss_public_t4_e3_hub = Event(id="her_ev_kiss_public_t4_e3_hub", label="hg_pr_kiss", req="states.her.tier == 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_kiss_public", subevents=["her_ev_kiss_public_t4_e3"])
default her_ev_kiss_public_t5_e1_hub = Event(id="her_ev_kiss_public_t5_e1_hub", label="hg_pr_kiss", req="states.her.tier >= 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_kiss_public", subevents=["her_ev_kiss_public_t5_e1"])
default her_ev_kiss_public_t5_e2_hub = Event(id="her_ev_kiss_public_t5_e2_hub", label="hg_pr_kiss", req="states.her.tier >= 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_kiss_public", subevents=["her_ev_kiss_public_t5_e2"])

default her_ev_handjob_public_t4_e1 = Event(id="her_ev_handjob_public_t4_e1", label="hg_pr_handjob_T4_E1", req="game.daytime==False")
default her_ev_handjob_public_t4_e2 = Event(id="her_ev_handjob_public_t4_e2", label="hg_pr_handjob_T4_E2", req="game.daytime==False")
default her_ev_handjob_public_t4_e3 = Event(id="her_ev_handjob_public_t4_e3", label="hg_pr_handjob_T4_E3", req="game.daytime==False")
default her_ev_handjob_public_t5_e1 = Event(id="her_ev_handjob_public_t5_e1", label="hg_pr_handjob_T5_E1", req="game.daytime==False")
default her_ev_handjob_public_t5_e2 = Event(id="her_ev_handjob_public_t5_e2", label="hg_pr_handjob_T5_E2", req="game.daytime==False")
default her_ev_handjob_public_t5_e3 = Event(id="her_ev_handjob_public_t5_e3", label="hg_pr_handjob_T5_E3", req="game.daytime==False")
default her_ev_handjob_public_t6_e1 = Event(id="her_ev_handjob_public_t6_e1", label="hg_pr_handjob_T6_intro_E1", req="game.daytime==False")
default her_ev_handjob_public_t6_e2 = Event(id="her_ev_handjob_public_t6_e2", label="hg_pr_handjob_T6_E2", req="game.daytime==False")
default her_ev_handjob_public_t6_e3 = Event(id="her_ev_handjob_public_t6_e3", label="hg_pr_handjob_T6_E3", req="game.daytime==False")

default her_ev_handjob_public_t1_to_t4 = Event(id="her_ev_handjob_public_t1_to_t4", label="hg_pr_handjob_fail", req="states.her.tier < 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_handjob_public")
default her_ev_handjob_public_t4_e1_hub = Event(id="her_ev_handjob_public_t4_e1_hub", label="hg_pr_handjob", req="states.her.tier == 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_handjob_public", subevents=["her_ev_handjob_public_t4_e1"])
default her_ev_handjob_public_t4_e2_hub = Event(id="her_ev_handjob_public_t4_e2_hub", label="hg_pr_handjob", req="states.her.tier == 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_handjob_public", subevents=["her_ev_handjob_public_t4_e2"])
default her_ev_handjob_public_t4_e3_hub = Event(id="her_ev_handjob_public_t4_e3_hub", label="hg_pr_handjob", req="states.her.tier == 4", autoenqueue=True, autodequeue=False, queue="her_eventqueue_handjob_public", subevents=["her_ev_handjob_public_t4_e3"])
default her_ev_handjob_public_t5_e1_hub = Event(id="her_ev_handjob_public_t5_e1_hub", label="hg_pr_handjob", req="states.her.tier == 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_handjob_public", subevents=["her_ev_handjob_public_t5_e1"])
default her_ev_handjob_public_t5_e2_hub = Event(id="her_ev_handjob_public_t5_e2_hub", label="hg_pr_handjob", req="states.her.tier == 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_handjob_public", subevents=["her_ev_handjob_public_t5_e2"])
default her_ev_handjob_public_t5_e3_hub = Event(id="her_ev_handjob_public_t5_e3_hub", label="hg_pr_handjob", req="states.her.tier == 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_handjob_public", subevents=["her_ev_handjob_public_t5_e3"])
default her_ev_handjob_public_t6_e1_hub = Event(id="her_ev_handjob_public_t6_e1_hub", label="hg_pr_handjob", req="states.her.tier >= 6", autoenqueue=True, autodequeue=False, queue="her_eventqueue_handjob_public", repeat=False, subevents=["her_ev_handjob_public_t6_e1"])
default her_ev_handjob_public_t6_e2_hub = Event(id="her_ev_handjob_public_t6_e2_hub", label="hg_pr_handjob", req="states.her.tier >= 6", autoenqueue=True, autodequeue=False, queue="her_eventqueue_handjob_public", subevents=["her_ev_handjob_public_t6_e2"])
default her_ev_handjob_public_t6_e3_hub = Event(id="her_ev_handjob_public_t6_e3_hub", label="hg_pr_handjob", req="states.her.tier >= 6", autoenqueue=True, autodequeue=False, queue="her_eventqueue_handjob_public", subevents=["her_ev_handjob_public_t6_e3"])

default her_ev_blowjob_public_t5_e1 = Event(id="her_ev_blowjob_public_t5_e1", label="hg_pr_blowjob_T5_E1", req="game.daytime==False")
default her_ev_blowjob_public_t5_e2 = Event(id="her_ev_blowjob_public_t5_e2", label="hg_pr_blowjob_T5_E2", req="game.daytime==False")
default her_ev_blowjob_public_t5_e3 = Event(id="her_ev_blowjob_public_t5_e3", label="hg_pr_blowjob_T5_E3", req="game.daytime==False")
default her_ev_blowjob_public_t6_e1 = Event(id="her_ev_blowjob_public_t6_e1", label="hg_pr_blowjob_T6_intro_E1", req="game.daytime==False")
default her_ev_blowjob_public_t6_e2 = Event(id="her_ev_blowjob_public_t6_e2", label="hg_pr_blowjob_T6_E2", req="game.daytime==False")
default her_ev_blowjob_public_t6_e3 = Event(id="her_ev_blowjob_public_t6_e3", label="hg_pr_blowjob_T6_E3", req="game.daytime==False")

default her_ev_blowjob_public_t1_to_t5 = Event(id="her_ev_blowjob_public_t1_to_t5", label="hg_pr_blowjob_fail", req="states.her.tier < 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_blowjob_public")
default her_ev_blowjob_public_t5_e1_hub = Event(id="her_ev_blowjob_public_t5_e1_hub", label="hg_pr_blowjob", req="states.her.tier == 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_blowjob_public", subevents=["her_ev_blowjob_public_t5_e1"])
default her_ev_blowjob_public_t5_e2_hub = Event(id="her_ev_blowjob_public_t5_e2_hub", label="hg_pr_blowjob", req="states.her.tier == 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_blowjob_public", subevents=["her_ev_blowjob_public_t5_e2"])
default her_ev_blowjob_public_t5_e3_hub = Event(id="her_ev_blowjob_public_t5_e3_hub", label="hg_pr_blowjob", req="states.her.tier == 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_blowjob_public", subevents=["her_ev_blowjob_public_t5_e3"])
default her_ev_blowjob_public_t6_e1_hub = Event(id="her_ev_blowjob_public_t6_e1_hub", label="hg_pr_blowjob", req="states.her.tier >= 6", autoenqueue=True, autodequeue=False, queue="her_eventqueue_blowjob_public", subevents=["her_ev_blowjob_public_t6_e1"])
default her_ev_blowjob_public_t6_e2_hub = Event(id="her_ev_blowjob_public_t6_e2_hub", label="hg_pr_blowjob", req="states.her.tier >= 6", autoenqueue=True, autodequeue=False, queue="her_eventqueue_blowjob_public", subevents=["her_ev_blowjob_public_t6_e2"])
default her_ev_blowjob_public_t6_e3_hub = Event(id="her_ev_blowjob_public_t6_e3_hub", label="hg_pr_blowjob", req="states.her.tier >= 6", autoenqueue=True, autodequeue=False, queue="her_eventqueue_blowjob_public", subevents=["her_ev_blowjob_public_t6_e3"])

default her_ev_sex_public_t6_e1 = Event(id="her_ev_sex_public_t6_e1", label="hg_pr_sex_T6_intro_E1", req="game.daytime==False")
default her_ev_sex_public_t6_e2 = Event(id="her_ev_sex_public_t6_e2", label="hg_pr_sex_T6_intro_E2", req="game.daytime==True", wait=1)
default her_ev_sex_public_t6_e3 = Event(id="her_ev_sex_public_t6_e3", label="hg_pr_sex_T6_E3", req="game.daytime==False")
default her_ev_sex_public_t6_e4 = Event(id="her_ev_sex_public_t6_e4", label="hg_pr_sex_T6_E4", req="game.daytime==False")

default her_ev_sex_public_t1_to_t6 = Event(id="her_ev_sex_public_t1_to_t6", label="hg_pr_sex_fail", req="states.her.tier < 6", autoenqueue=True, autodequeue=False, queue="her_eventqueue_sex_public")
default her_ev_sex_public_t6_e1_hub = Event(id="her_ev_sex_public_t6_e1_hub", label="hg_pr_sex", req="states.her.tier >= 6", autoenqueue=True, autodequeue=False, repeat=False, queue="her_eventqueue_sex_public", subevents=["her_ev_sex_public_t6_e1", "her_ev_sex_public_t6_e2"])
default her_ev_sex_public_t6_e2_hub = Event(id="her_ev_sex_public_t6_e2_hub", label="hg_pr_sex", req="states.her.tier >= 6", autoenqueue=True, autodequeue=False, queue="her_eventqueue_sex_public", subevents=["her_ev_sex_public_t6_e3"])
default her_ev_sex_public_t6_e3_hub = Event(id="her_ev_sex_public_t6_e3_hub", label="hg_pr_sex", req="states.her.tier >= 6", autoenqueue=True, autodequeue=False, queue="her_eventqueue_sex_public", subevents=["her_ev_sex_public_t6_e4"])

default her_ev_cumslut_public_t5_e1 = Event(id="her_ev_cumslut_public_t5_e1", label="hg_pr_cumslut_e1_return", req="game.daytime==False")
default her_ev_cumslut_public_t5_e2 = Event(id="her_ev_cumslut_public_t5_e2", label="hg_pr_cumslut_e2_return", req="game.daytime==False")
default her_ev_cumslut_public_t5_e3 = Event(id="her_ev_cumslut_public_t5_e3", label="hg_pr_cumslut_e3_return", req="game.daytime==False")

default her_ev_cumslut_public_t1_to_t5 = Event(id="her_ev_cumslut_public_t1_to_t5", label="hg_pr_cumslut_fail", req="states.her.tier < 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_cumslut_public")
default her_ev_cumslut_public_t5_e1_hub = Event(id="her_ev_cumslut_public_t5_e1_hub", label="hg_pr_cumslut_e1", req="states.her.tier >= 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_cumslut_public", subevents=["her_ev_cumslut_public_t5_e1"])
default her_ev_cumslut_public_t5_e2_hub = Event(id="her_ev_cumslut_public_t5_e2_hub", label="hg_pr_cumslut_e2", req="states.her.tier >= 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_cumslut_public", subevents=["her_ev_cumslut_public_t5_e2"])
default her_ev_cumslut_public_t5_e3_hub = Event(id="her_ev_cumslut_public_t5_e3_hub", label="hg_pr_cumslut_e3", req="states.her.tier >= 5", autoenqueue=True, autodequeue=False, queue="her_eventqueue_cumslut_public", subevents=["her_ev_cumslut_public_t5_e3"])

define hermione_requests = [
    ("her_eventqueue_flirt_students", "Flirt with students!"),
    ("her_eventqueue_flirt_teachers", "Flirt with teachers!"),
    ("her_eventqueue_grope_public", "Let them grope you!"),
    ("her_eventqueue_flash_public", "Flash your tits!"),
    ("her_eventqueue_kiss_public", "Kiss a girl!"),
    ("her_eventqueue_handjob_public", "Give a handjob!"),
    ("her_eventqueue_blowjob_public", "Give a blowjob!"),
    ("her_eventqueue_cumslut_public", "Act like a cumslut!"),
    ("her_eventqueue_sex_public", "Have sex!")
]