
default sna_ev_hangouts_wine_e1 = Event(id="sna_ev_hangouts_wine_e1", label="ss_he_wine_intro", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_drinking")
default sna_ev_hangouts_wine_e2 = Event(id="sna_ev_hangouts_wine_e2", label="ss_he_wine_repeat", autoenqueue=True, autodequeue=False, queue="sna_eventqueue_hangouts_drinking")
default sna_ev_hangouts_wine_e3 = Event(id="sna_ev_hangouts_wine_e3", label="ss_he_wine_intro_E2", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_drinking")

default sna_ev_hangouts_stories_e1 = Event(id="sna_ev_hangouts_stories_e1", label="ss_he_story_E1", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e2 = Event(id="sna_ev_hangouts_stories_e2", label="ss_he_story_intro_E2", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e3 = Event(id="sna_ev_hangouts_stories_e3", label="ss_he_story_intro_E3", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e4 = Event(id="sna_ev_hangouts_stories_e4", label="ss_he_story_intro_E4", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e5 = Event(id="sna_ev_hangouts_stories_e5", label="ss_he_story_intro_E5", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e6 = Event(id="sna_ev_hangouts_stories_e6", label="ss_he_story_E6", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e7 = Event(id="sna_ev_hangouts_stories_e7", label="ss_he_story_intro_E7", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e8 = Event(id="sna_ev_hangouts_stories_e8", label="ss_he_story_intro_E8", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e9 = Event(id="sna_ev_hangouts_stories_e9", label="ss_he_story_intro_E9", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e10 = Event(id="sna_ev_hangouts_stories_e10", label="ss_he_story_intro_E10", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e11 = Event(id="sna_ev_hangouts_stories_e11", label="ss_he_story_intro_E11", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e12 = Event(id="sna_ev_hangouts_stories_e12", label="ss_he_story_intro_E12", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e13 = Event(id="sna_ev_hangouts_stories_e13", label="ss_he_story_intro_E13", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e14 = Event(id="sna_ev_hangouts_stories_e14", label="ss_he_story_E14", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")
default sna_ev_hangouts_stories_e15 = Event(id="sna_ev_hangouts_stories_e15", label="ss_he_story_intro_E15", autoenqueue=True, autodequeue=False, repeat=False, queue="sna_eventqueue_hangouts_stories")